import { Roboto } from 'next/font/google'
import './globals.css';
import { Toaster } from "react-hot-toast";
import  AppProvider  from "../components/AppContext";
import Header from '../components/layout/Header';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'PABLO',
  description: 'Generated by create next app',
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
            PABLO  &copy; 2012 All rights reserved
            </footer>
          </AppProvider>

        </main>
      </body>
    </html>
  )
}



